name: Running tests

# Trigger on all branches
on:
    push:
        branches: '*'
    pull_request:
        branches: ['master']

jobs:
    # Test job: runs tests, linting
    test:
        runs-on: ubuntu-latest

        steps:
            # Checkout repository code
            - uses: actions/checkout@v3

            # Setup Node.js environment
            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: '18'
                  cache: 'npm'

            # Install project dependencies
            - name: Install dependencies
              run: npm ci

            # Run unit tests
            - name: Run tests
              run: npx jest
